name: Deploy

on:
  push:
    branches: [main]
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - closed
      - reopened

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: deployed-website
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run generate  # Adjust based on the actual build command
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'Myself/Issues'  # This is where the site is generated from
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
